SELECT
    T1.FOOD_TYPE,T1.REST_ID,T1.REST_NAME,T1.FAVORITES
FROM
    REST_INFO T1
    RIGHT OUTER JOIN (SELECT
                    FOOD_TYPE,MAX(FAVORITES) AS FAVORITES
                FROM
                    REST_INFO
                GROUP BY
                    FOOD_TYPE) T2
    ON T1.FAVORITES = T2.FAVORITES AND T1.FOOD_TYPE = T2.FOOD_TYPE
ORDER BY
    T1.FOOD_TYPE DESC;
